clean:
	./gradlew clean
build:
	./gradlew build
install:
	./gradlew installDist
setup:
	./gradlew clean installDist
test:
	./gradlew test
report:
	./gradlew jacocoTestReport
lint:
	./gradlew checkstyleMain
.PHONY: build clean install setup test report lint
