name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5'
          arguments: 'build'
          build-root-directory: 'app'

      - name: Run checkstyleMain
        run: cd app && ./gradlew checkstyleMain

      - name: Run tests
        run: cd app && ./gradlew test


      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: 'app/src/main/java'
        with:
          coverageCommand: './gradlew jacocoTestReport'
          coverageLocations: '${{ github.workspace }}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco'
